### ISSUE TITLE
Bend90.py 3D simulation broken?

### ISSUE THREAD

**Issue by WillE9a** [stanfordnqp/spins-b#55] opened 2021-03-14 17:17 UTC
I am able to run the 2D version of bend90 perfectly fine, but it results in an error when ran as a 3D sim (maxwell solver server is up and running of course). Here is the output I get:
![image](https://user-images.githubusercontent.com/47069896/111077389-f7c1db00-84c6-11eb-9b80-7ec771497e5e.png)

Note that our cluster's installation of spins-b-maxwell was through singularity rather than docker. I've brought this up to our HPC staff to see if they had any insight, and they recommended that I open an issue here since the simulations break only when the 3Dsim boolean is set to true. Any help is appreciated, thank you!

**Comment by JesseLu** [comment] 2021-04-05 04:00
Hi! This may be caused by a breaking change in the hdf5 api after version 3, just a guess. What version of hdf5 do you have installed?

**Comment by JesseLu** [comment] 2021-04-07 22:21
Closing for now.

**Closed by JesseLu** 2021-04-07 22:21 UTC

**Comment by LYX-Rain** [comment] 2021-11-28 11:31
@JesseLu which version of h5py should I use

**Comment by kaipengliuHIT** [comment] 2022-02-28 12:40
> @JesseLu which version of h5py should I use

hi！I get the same error in a new computer with RTX 3050, have you solved this problem
?

**Comment by kaipengliuHIT** [comment] 2022-02-28 12:46
but the environment constructed on an old computer in 2020 can run normally.

**Comment by wuchu314** [comment] 2022-08-26 07:20
> > @JesseLu which version of h5py should I use
> 
> hi！I get the same error in a new computer with RTX 3050, have you solved this problem ?

Excuse me,I have the same error even after I installed a lower version of h5py. Have you solved the problem and run maxwell-b in your new computer successfully？Looking forward to your apply!

**Comment by WillE9a** [comment] 2022-08-26 15:11
Hey @wuchu314, here is the package list I used to get spins-b installed in a conda environment and running on our cluster:

- conda install git -y
- conda install -c conda-forge numpy -y
- conda install -c conda-forge mkl -y
- conda install -c conda-forge shapely -y
- conda install -c conda-forge dill -y
- conda install -c conda-forge flatdict -y
- conda install -c conda-forge gdspy -y
- conda install -c conda-forge jsonschema -y
- conda install -c conda-forge matplotlib -y
- conda install -c conda-forge pyyaml -y
- conda install -c conda-forge requests -y
- conda install -c conda-forge schematics -y
- conda install -c conda-forge scipy -y
- conda install -c conda-forge autograd -y
- conda install -c conda-forge nlopt -y
- conda install -c conda-forge h5py -y
- conda install -c conda-forge pandas -y
- conda install -c conda-forge mpi4py -y
- conda install -c conda-forge cudatoolkit -y
- conda install -c conda-forge pycuda=2020.1 -y
- pip3 install Jinja2==2.10.3

I installed spins using pip and the "--use-feature=in-tree-build" option. Then, copied the "spins-b/spins," "maxwell-b/maxwell-server," and "maxwell-b/maxwell-solver" directories to the conda "site-packages" directory

After that, I had to downgrade some packages to get rid of some other errors/warnings:
- pyyaml=5.4.1
- markupsafe==2.0.1

I was able to run the wdm2.py example, so it seems like spins was running correctly.

I hope that helps!

**Comment by wuchu314** [comment] 2022-10-31 13:27
> 

Hello,sorry to bother again~I wonder if you are using Windows or linux. And after copy the _maxwell_ file to the corresponding directory _site-packages_, what do I need to do next to make the server running?I did every steps as you said above but still get some errors，indicating that the maxwell server is not working properly.Thank you! 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/67185328/199016075-b145db2d-eac9-43e7-b38a-58c06b8670c3.png">

**Comment by WillE9a** [comment] 2022-10-31 15:39
I am running this through my University's computer cluster, which uses Linux. I have never tried using Windows to run spins, so I won't be able to provide much help with that unfortunately. Here is part of my script I use to start 3D optimizations. It does the following:

1. Activates the conda environment you installed spins in
2. Creates and moves files (GDS design files, the optimization code, and any analysis code you might have) to a separate 'results' directory. This is mostly to save cluster storage space since each user is only allocated so much.
3. Creates a "temporary maxwell" directory where all the output files between maxwell server/solver will be held. Important to export that path to an environment variable "MAXWELL_SERVER_FILES" (I think this is what you need to have, so the server/solver know where to talk to each other, so to speak)
4. Loads CUDA
5. The port should default to 9041, so you can skip where I setup custom port numbers (this was again a cluster specific fix so I could have multiple server instances started instead of a single one that all jobs would use)
6. Start the webserver on the desired port (probably 9041)
7. Start the sim server with the number of GPUs you want to use
8. Run optimization code

![start_job](https://user-images.githubusercontent.com/47069896/199043446-f719acc9-97c6-4e1d-b0d9-e37e80c25a6f.PNG)

Hope that helps,

Will

**Comment by wuchu314** [comment] 2022-11-12 04:29
Thank you so much Will! Giving up the possible compatibility issues of building virtual machine with wsl2（in windows）, I finally finished debugging the 3D simulation in linux. As a beginner lacking knowledge, I had previously been running both the simulation file and the server file (maxwell) in one docker container. This mistake caused the port occupation problem. Thank you for your very careful guidance, it made me very impressed.
